sudo: required

language: node_js
node_js:
  - node

before_install:
  - openssl aes-256-cbc -K $encrypted_1e675daaeb1c_key -iv $encrypted_1e675daaeb1c_iv -in ./keys/travis-service-account.json.enc -out ./keys/travis-service-account.json -d

install:
  - npm install

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  - provider: gae
    project: lionel-tay
    keyfile: ./keys/travis-service-account.json
    config: "dispatch.yaml"
    verbosity: debug
    skip_cleanup: true
    on: master

  - provider: gae
    project: lionel-tay
    keyfile: ./keys/travis-service-account.json
    config: "./prod.yaml"
    verbosity: debug
    skip_cleanup: true
    on: master

  - provider: gae
    project: lionel-tay
    keyfile: ./keys/travis-service-account.json
    config: "dispatch.yaml"
    verbosity: debug
    skip_cleanup: true
    on: dev

  - provider: gae
    project: lionel-tay
    keyfile: ./keys/travis-service-account.json
    config: "./dev.yaml"
    verbosity: debug
    skip_cleanup: true
    on: dev
