sudo: required
language: node_js
node_js:
  - "10"
before_install:
  - openssl aes-256-cbc -K $encrypted_8517169ff567_key -iv $encrypted_8517169ff567_iv
    -in ./keys/travis-deploy-onyami-service-account.json.enc -out ./keys/travis-deploy-onyami-service-account.json
    -d

install:
  - npm install

script:
  - npm run test

before_deploy:
  - npm run build

deploy:
  - provider: gae
    project: onyami
    keyfile: "./keys/travis-deploy-onyami-service-account.json"
    config: dispatch.yaml
    verbosity: debug
    skip_cleanup: true
    on: master
  - provider: gae
    project: onyami
    keyfile: "./keys/travis-deploy-onyami-service-account.json"
    config: "./prod.yaml"
    verbosity: debug
    skip_cleanup: true
    on: master
  - provider: gae
    project: onyami
    keyfile: "./keys/travis-deploy-onyami-service-account.json"
    config: dispatch.yaml
    verbosity: debug
    skip_cleanup: true
    on: dev
  - provider: gae
    project: onyami
    keyfile: "./keys/travis-deploy-onyami-service-account.json"
    config: "./dev.yaml"
    verbosity: debug
    skip_cleanup: true
    on: dev
